spring:
  application:
    name: maplr-sugar-shack
  flyway:
    enabled: true
    locations: classpath:db/migration/,classpath:db/testdata/
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html